### ISSUE TITLE
Bulma Extension Request: Pricing Tables

### ISSUE THREAD

**Issue by Log1x** [Wikiki/wikiki.github.io#1]
😄 Didn't know where else to get in contact with you-- hopefully this is okay.

Would you mind doing some clean pricing tables as a Bulma extension? It'd be much appreciated.

-Brandon

**Comment by Wikiki** [comment]
Hi,

this is the perfect place ;-)

I'll add the pricing-table extension on my To-Do list.
Thanks for the request.

For your information this page is currently under development and will centralize all my extension's documentation.

Regards

**Comment by Wikiki** [comment]
Hi,

you can find a first basic version of this new extension here: https://wikiki.github.io/bulma-extensions/pricing-table

Regards
